### ISSUE TITLE
Automated: Protex scan failed

### ISSUE THREAD

**Issue by auto-Integrator** [qlik-oss/picasso.js#111]
A BlackDuck Protex scan failed on this repository.

Number of files needing identification: 18

If you are unsure how this process works, please contact trunk team on Slack.

No more automated issues will be created on this repository until this issue
is closed.

*Please prioritize and solve this as soon as possible. If the files
has been identified already, you may ignore and close this issue.*

**Comment by peol** [comment]
Fixed.
