### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by curran** [qlik-oss/picasso.js#13]
Greetings,

Are tooltips (more details on hover) on the roadmap for this library?

**Comment by cookiejest** [comment]
Is it possible you can share the roadmap with us?

**Comment by miralemd** [comment]
Will get one out in a few days :)

**Comment by carlhannes** [comment]
Hi! We're working on a tooltip component, but until then you can check out this example by @cbt1 on how to create your own custom tooltip component in picasso.js: [](https://beta.observablehq.com/@cbt1/picasso-js-creating-your-own-tooltip-component)

**Comment by curran** [comment]
@carlhannes Awesome! Thanks for following up. That custom tooltip looks great.

Just curious, what is the data source for that Solar System data? Pretty neat data!

**Comment by cbt1** [comment]
Implemented by: #147 

Available in picasso.js v0.12.0
