### ISSUE TITLE
Axis do not adjust when using the sum reducer.

### ISSUE THREAD

**Issue by adriangoransson** [qlik-oss/picasso.js#141]
### Description

When using the box and axis component together for a bar chart, the axis will automatically adjust to fit the maximum value. This does not happen when a bar is the sum of multiple values.

### Steps to Reproduce

https://beta.observablehq.com/d/dca683508b1ea7ea

Fork of https://beta.observablehq.com/@miralemd/picasso-js-bar-chart with the following picasso diff
```diff
29a30,31
>           trackBy: v => v,
>           reduce: 'first',
32,33c34,41
<             start: 0,
<             end: { field: 'Sales' }
---
>             start: {
>               field: 'Month',
>               reduce: () => 0,
>             },
>             end: {
>               field: 'Sales',
>               reduce: 'sum',
>             }
```

and data diff

```diff
12a13,17
>   arr.push(['Jan', 15000]);
>   arr.push(['Jan', 5000]);
```

##### Expected behavior

The vertical axis should be high enough to fit the `Jan` bar that has a value of at least 20000.

##### Actual behavior

The vertical axis is stuck at a max of 15000 which is the highest single value for `Jan`.

### Versions

* picasso.js: 0.10.4
* Browser: Firefox 61.0.1

**Comment by cbt1** [comment]
It's not an issue in the axis component. It just happens to show it. The scale `y` will always deduce it's min and max from the min/max value of the data. Which just happens to be 5000/15000.

A work around could be to create your own reduce function on the scales `max` property and calculate the correct value there. As there seem to be no way to infer it from the data settings.

**Comment by adriangoransson** [comment]
😢 

Thanks for the help! This did the trick.

```javascript
// dimension, measure = chart.dataset().fields()[dimension/measure index]
const dim = dimension.items();
const msr = measure.items();

let max = 0;
msr.reduce((sum, m, i) => {
  const sumIndex = dim.findIndex(d => d === dim[i]);
  sum[sumIndex] = (sum[sumIndex] || 0) + m;

  max = Math.max(max, sum[sumIndex]);
  return sum;
}, []);

return max;
```
