### ISSUE TITLE
Line component orientation doesn't update

### ISSUE THREAD

**Issue by Hannesfornell** [qlik-oss/picasso.js#144]
### Description

When updating the orientation property of a line component with picasso.update() the rendered orientation of the line doesn't change. When inspecting the component you can observe that the property updates which implies that picasso doesn't recognize the change and hence ignore updating the chart. 

### Steps to Reproduce

1. Create a line component with orientation property
2. Use picasso.update({settings: updatedSettings) where updatedSettings is the original setting config where only the orientation property has been changed.

##### Expected behavior

The line component would re-render and have its orientation changed.

##### Actual behavior

The component has the same orientation as before even though the property has changed.

### Versions

* picasso.js: 0.10.0
* Browser: 67.0.3396.99

**Comment by AnalyticsEarth** [comment]
I also have seen this issue, only on the line component. I have to recreate the chart object if editing the line component settings. All other layers work fine observing a new config with update function.
