### ISSUE TITLE
Tooltip feedback/issues

### ISSUE THREAD

**Issue by peol** [qlik-oss/picasso.js#177]
When I tried using the new tooltip component, a few things constrained me/caused issues so I thought I'd give you my $0.05.

* The `pic-tooltip` element also receives classes `0 1 2 3 4 5 6`
* Initially a bit confused about the differences between `extract()` and `content()` members (but I guess it's primarily semantic)
* The `tooltipClass` setting does not seem to do anything?
* No (easy) way of overriding the tooltip styling since it is applied inline on different elements (e.g. even if I modify `pic-tooltip` element, the `pic-tooltip-content` element has its own inline style which overrides it)

My proposal would be to either inject a `<style>` element with picasso classes and define the styling there instead of using inline styles which cannot be overridden, or at least separate the styling CSS from the positional CSS and clearly document where one could pass in their custom (inline) CSS.

**Comment by cbt1** [comment]
Hi, thanks for the feedback!

* `tooltipClass` must be an object with the following structure object<string, boolean>
* `extract` and `content` are indeed semantic
* `tooltipClass` should be appended to the tooltip root element as a list of classes
* Agree that the inline styling should be optional in some fashion, but not yet decided on how it's best done

**Comment by peol** [comment]
Thanks, closing this issue since it's working as-designed :)
