### ISSUE TITLE
documentation typos

### ISSUE THREAD

**Issue by skokenes** [qlik-oss/picasso.js#23]
Working through the q plugin docs at https://picassojs.com/docs/plugin-q.html and noticing some issues:

```
import picasso from 'picasso.js';
import picassoQ from 'picasso-plugin-q';

picasso.use(pluginQ); // register
```

should say .use(picassoQ), not .use(pluginQ):
```
import picasso from 'picasso.js';
import picassoQ from 'picasso-plugin-q';

picasso.use(picassoQ); // register
```

---
```
const ds = picasso.data('q')({
  key: 'qHyperCube', // path to the hypercube from the layout
  data: layout.qHypercube
});
```

has qHyperCube misspelled. should say:
```
const ds = picasso.data('q')({
  key: 'qHyperCube', // path to the hypercube from the layout
  data: layout.qHyperCube
});
```

Also, the "key" string doesn't seem to matter, so not sure why it's needed at this point in time.

**Comment by miralemd** [comment]
ah, thanks for noticing!

**Comment by miralemd** [comment]
the `key` property in this particular case is there primarily for the sake of consistency with when sending multiple hypercubes to a chart instance. It is used when identifying the origin of a field.

Use case: _find the first measure with qMax > 100_ :
```js
const field = ds.field(f => f.type() === 'measure' && f.raw().qMax > 100);
console.log(field.id()); // qHyperCube/qMeasureInfo/2
```
