### ISSUE TITLE
Should we use pluginQ or picassoQ?

### ISSUE THREAD

**Issue by wuzhong-zhu** [qlik-oss/picasso.js#24]
### Description
Should we use pluginQ or picassoQ?

### Steps to Reproduce
In plugin-q.md it stats that use 
picasso.use(pluginQ); // register
to register pluginQ
https://github.com/qlik-oss/picasso.js/blob/master/docs/dist/plugin-q.md

But it does not work for the latest version.
From other resources i found picassoQ which works.
Could you update this?

**Comment by miralemd** [comment]
`pluginQ` is a typo (#23), should use `picassoQ`
