### ISSUE TITLE
Not showing layers with same name

### ISSUE THREAD

**Issue by andrei258258** [qlik-oss/picasso.js#295]
Hi,
when I name 2 layers with the same name, only the first one shows in the chart:
![image](https://user-images.githubusercontent.com/22275358/51856879-f994a880-2317-11e9-88b4-f2a765660b8c.png)

In the image, I named 2 layers "%Stock Out", but only the layer line shows in the chart.

I'm using the Picasso v0.4.0 in the November/18 Qliksense Enterprise version.

Thanks

**Comment by miralemd** [comment]
Hi Andrei,

I think you meant to create the issue in here instead: https://github.com/AnalyticsEarth/aePicassoChart
