### ISSUE TITLE
PicassoJS extension not found on server error

### ISSUE THREAD

**Issue by MikeDeane** [qlik-oss/picasso.js#317]
## 🐛 Bug report

(A clear and concise description of what the bug is.)

### Steps to Reproduce

1. (Step one)
1. (Step two)
1. ...

### Expected behavior

(A clear and concise description of what you expected to happen.)

### Actual behavior

(A clear and concise description of what actually happened.)

### Versions

* picasso.js: (x.y.z)
* Browser: ?

### Additional context

(Add any other context, link to demo or screenshots about the issue.)

**Comment by MikeDeane** [comment]
PicassoJS extension not found on server error:

Works in QS Desktop, does not work in server.  Some extension examples have a mapping to localhost that needs to change, that usually fixes a similar error found in those extensions.

picasso.js v4
chrome v 72.0.3626.121 (Official Build) (64-bit)

**Comment by miralemd** [comment]
@MikeDeane `picasso.js` is a standalone library - if you find issues in the products using `picasso.js` you should report that in the product itself.
