### ISSUE TITLE
Extract fields from Pivot hypercube

### ISSUE THREAD

**Issue by taan11** [qlik-oss/picasso.js#478]
Hi guys, 

I am struggling extracting fileds value from a pivot hypercube (qMode='P') using the picasso-q-plugin: 
I have tried this:

`const qHyperCube=qLayout.qHyperCube`
`picasso.use(picassoQ);`
` const ds = picasso.data('q')({`
`    key:'qHyperCube',`
`    data:qHyperCube`
`  })`
`const dim0 = ds.extract({field:'qDimensionInfo/0'}) `

but dim0 is an empty array as well as fieldItems (below) while raw, key and id contains the expected values

`const dsFields = ds.fields()`
`const fieldItems = fields[0].items()`
`const raw = fields[0].raw()`
`const id = fields[0].id()`
`const key = fields[0].key()`
 
Could you please let me know if I am missing something?
Thanks a lot for your help.
Paolo

**Comment by miralemd** [comment]
Hi @taan11 

There's unfortunately no support yet for `qMode: 'P'` - the complexities of the pivot structure makes it bit trickier to figure out exactly how to extract the values

**Comment by taan11** [comment]
ok, thanks, I had figured it out, but I wanted to be sure.
If you had time, it could be useful to explicitly tell this in docs.
Ciao
Paolo
