### ISSUE TITLE
Add new attributes like: "data-* attributes" before chart is mounting 

### ISSUE THREAD

**Issue by AlexanderGoerlich** [qlik-oss/picasso.js#63]
### Description

Hi there,

how can i manipulate the DOM before mounted in for example add tooltip from bootstrap like this one:

![demo](https://user-images.githubusercontent.com/13659581/38420341-ab09453a-39a3-11e8-97a2-070a81aaa00f.JPG)

In the moment I go this way:

1.  when you go mouseover on tag "rect" 

`<rect fill="#ff0000" stroke="#000" stroke-width="0" x="219.40540540540542" width="29.91891891891892" y="179.57231047828998" height="320.3979910006436" data-value="4" data-label="Fr"></rect>`

2. then I add new attributes with infos :

`data-toggle="tooltip" data-placement="top" title="15941,05"`

3. after that I call: 

`  $('[data-toggle="tooltip"]').tooltip();`

4. then you see a cool tooltip with bootstrap

I know there better ways for that solution.... but how?

----------------------------------------------------------------------------

And how do I get 2 qMeasureInfos side by side, which lie on the same x-axis?

![demo2](https://user-images.githubusercontent.com/13659581/38421346-1a144f76-39a7-11e8-8445-1eb8527a13db.JPG)

Thank you picasso.js

**Comment by AlexanderGoerlich** [comment]
ok... i have a solution for part one:
> And how do I get 2 qMeasureInfos side by side, which lie on the same x-axis?

you need two x-axis:

`
 x: { //red 
                            data: {
                                extract: {
                                    field: "qDimensionInfo/0"
                                },
                            },
                            padding: 0.8,
                            align: 0.135
                        },
                        x2: {
                            data: {
                                extract: {
                                    field: "qDimensionInfo/0"
                                },
                            },
                            padding: 0.8,
                            align: 0
                        },`


![unbenannt](https://user-images.githubusercontent.com/13659581/38489378-80c15c1e-3be6-11e8-8477-aa779baf549d.JPG)

**Comment by cbt1** [comment]
@AlexanderGoerlich Have you looked at [this](https://beta.observablehq.com/@cbt1/picasso-js-creating-your-own-tooltip-component) tooltip example?

**Comment by AlexanderGoerlich** [comment]
@cbt1 yes i have!

**Comment by miralemd** [comment]
@AlexanderGoerlich you can have multiple measures on the same axis by offsetting each bar, see [this example](https://beta.observablehq.com/@miralemd/picasso-js-grouped-bar-chart)

**Comment by AlexanderGoerlich** [comment]
@miralemd   thx for that!

**Comment by cbt1** [comment]
Consider this solved.
