### ISSUE TITLE
Scrolling for charts

### ISSUE THREAD

**Issue by jansivans** [qlik-oss/picasso.js#643]
Hello.
Does picasso.js support scrolling inside charts like in Qlik?
![CleanShot 2021-11-04 at 15 30 13](https://user-images.githubusercontent.com/5667073/140322209-28a301be-a8f4-40aa-b641-b7cb179bd79d.png)

**Comment by cbt1** [comment]
Hi @jansivans,

There is no API in picasso that lets you do it "out-of-the-box". But the image you have attached is actually from a chart created using picasso. So it's definitely possible but unfortunately there is no guide or help documented at the moment.

**Comment by jansivans** [comment]
@cbt1 thanks for a quick answer!
I have seen that `@nebula.js/sn-bar-chart` supports scrolling, but unfortunately can't find source code of it.
Do you know if it is open-sourced?

**Comment by cbt1** [comment]
It is not

**Comment by veinfors** [comment]
Hi @jansivans! This could give you some ideas on how to get scrolling in place: https://stackblitz.com/edit/3scrolls?file=index.js

**Comment by jansivans** [comment]
@veinfors thanks a lot! Looks promising.

**Comment by cbt1** [comment]
> Hi @jansivans! This could give you some ideas on how to get scrolling in place: https://stackblitz.com/edit/3scrolls?file=index.js

Awesome! Had forgotten about that one
