### ISSUE TITLE
3D transform on iOS 11 iPhone SE makes the chart dance when scrolling. 

### ISSUE THREAD

**Issue by KFredberg** [qlik-oss/picasso.js#7]
Picassojs.com the chart is 3D transform on iOS 11 iPhone SE when scrolling. Looks like the chart dances. The width of the content extends when the chart rotated and reveals a white background.

**Comment by KFredberg** [comment]
![c6ebaba4-bdb1-44aa-9813-a1e7f81f4491](https://user-images.githubusercontent.com/121590/36060568-a8f8991c-0e4c-11e8-9897-9fc476ad29f7.png)

**Comment by konne** [comment]
this also occurs in my local FF under Win10
