### ISSUE TITLE
The graph injection fail silently, no error.

### ISSUE THREAD

**Issue by SuperstrongBE** [qlik-oss/picasso.js#70]
### Description
First use of picasso.js in a ES6 project. Code are copy pasted from the github project page.

[Description of the issue]
The graph injection fail silently.

### Steps to Reproduce
With webpack, picasso installed via NPM. 
1. [Step one]
import picasso as dependency 
2. [Step two]
copy paste code from https://github.com/qlik-oss/picasso.js

##### Expected behavior
The plot graph rendered in the element specified in the definition.

##### Actual behavior
Graph is not rendered and dom element specified in the definition  remain empty (id checked more then twice :) ). 
Created and mounted callback are fired. Mounted dom element specified params is the expected dom element specified in the definition. No error in console.

### Versions

* picasso.js: 
 "picasso.js": "^0.7.0"
* Browser: 
Chrome Version 66.0.3359.139 (Build officiel) (64 bits)
Firefox 59.0.2 (64 bits)
* [Other relevant versions]

**Comment by miralemd** [comment]
@SuperstrongBE Thanks for bringing this up, the example is updated - could you check if it works for you now?
