### ISSUE TITLE
add https for picassojs.com

### ISSUE THREAD

**Issue by konne** [qlik-oss/picasso.js#8]
please add a http -> https redirect and a correct https for picassojs.com

**Comment by carlhannes** [comment]
Sadly github pages doesn’t seem to support https out-of-the-box for custom domains but we’ll look into fixing this

**Comment by carlhannes** [comment]
SSL cert is underway and should be live within 24 hours

**Comment by stefanwalther** [comment]
Always these German guys and their security concerns ... @konne  ;-)
